name: run codefresh pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Codefresh pipeline runner
        uses: codefresh-io/codefresh-pipeline-runner@v5
        env:
          PIPELINE_NAME: 'codefresh-io/cf-yaml-validator/cf-yaml-validator'
          TRIGGER_NAME: 'codefresh-io/cf-yaml-validator_1'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        id: run-pipeline


